config/routes.rb
Rails.application.routes.draw do

	root 'pages#home'
  get '/about', to: 'pages#about'
  get '/rules', to: 'pages#rules'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :games

  get 'signup', to: 'users#new'
  resources :users, except: [:new]
end

app/models/game.rb
 class Game < ActiveRecord::Base
	belongs_to :user
	validates :type_of_game, presence: :true, length: { minimum: 3, maximum: 19 }
	validates :number, presence: :true, length: { minimum: 1, maximum: 1 }
	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :games, dependent: :destroy
	before_save { self.email = email.downcase }
	validates :username, presence: true,
	          uniqueness: { case_sensitive: false },
	          length: { minimum: 3, maximum: 25 }
	EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 105 },
	           uniqueness: { case_sensitive: false },
	           format: { with: EMAIL_REGEX }
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_nav, :set_footer

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user?
    if !logged_in?
      flash[:danger] = "You must be logged in to preforme that action"
      redirect_to root_path
    end
  end

  def set_nav
  	@nav_true = true
  end

  def set_footer
  	@footer_true = true
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	before_action :set_game, only: [:edit, :update, :show, :destroy]
	before_action :require_user?, except: [:index, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]

	def index
		@games = Game.paginate(page: params[:page], per_page: 7)
	end

	def new
		@game = Game.new
	end

	def edit

	end

	def update
		if @game.update(game_params)
			flash[:success] = "Game was successfully updated."
			redirect_to game_path(@game)
		else
			render 'edit'
		end
	end

	def create
		@game = Game.new(game_params)
		@game.user = current_user
		if @game.save
			flash[:success] = "The game was created, you're welcome..."
			redirect_to game_path(@game)
		else
			render 'new'
		end
	end

	def show

	end

	def destroy
		@game.destroy
		flash[:danger] = "Game was successfully deleted."
		redirect_to games_path
	end

	private
		def game_params
			params.require(:game).permit(:type_of_game, :number, :Player1_id, :Player2_id, :winner, :skunk, :perfect_hand, :muggins_points, :misdeals)
		end

		def set_game
			@game = Game.find(params[:id])
		end

		def require_same_user
			if current_user != @game.user and !current_user.admin?
				flash[:danger] = "You can only edit or delete your own article"
				redirect_to root_path
			end
		end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	redirect_to games_path if logged_in?
  end

  def login
  	@nav_true = false
  	@footer_true = false
  end

  def about

  end

  def rules

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new

	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:success] = "Successful login"
			redirect_to user_path(user)
		else
			flash.now[:danger] = "There was something wrong with your login"
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "You are logged out"
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :update, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]
	before_action :require_admin, only: [:destroy]

	def index
		@users = User.paginate(page: params[:page], per_page: 2)
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:success] = "Welcome to GoochMe #{@user.username}"
			redirect_to user_path(@user)
		else
			render 'new'
		end
	end

	def edit

	end

	def update
		if @user.update(user_params)
			flash[:success] = "Your account was updated"
			redirect_to games_path
		else
			render 'edit'
		end
	end

	def show
		@user_games = @user.games.paginate(page: params[:page], per_page: 5)
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:danger] = "User and all games have been deleted"
		redirect_to users_path
	end

	private

	def user_params
		params.require(:user).permit(:username, :email, :password)
	end

	def set_user
		@user = User.find(params[:id])
	end

	def require_same_user
		if current_user != @user and !current_user.admin?
			flash[:danger] = "You can only edit your own account"
			redirect_to root_path
		end
	end

	def require_admin
		if logged_in? and !current_user.admin?
			flash[:danger] = "Only Admin users can preform this action"
			redirect_to root_path
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.username, class: "img-circle")
	end
end

app/views/games/_form.html.erb
<%= render 'shared/errors', obj: @game %>
<div class="row">
	<div class="col-xs-12">
		<%= form_for(@game, :html => {class: "form-horizontal", role: "form"}) do |f| %>
			<div class="form-group">
				<div class="control-label col-sm-offset-2 col-sm-2">
					<%= f.label :type_of_game %>
				</div>
				<div class="col-sm-4">
					<%= f.text_field :type_of_game, class: "form-control", placeholder: "Game Type", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-offset-2 col-sm-2">
					<%= f.label :number %>
				</div>
				<div class="col-sm-4">
					<%= f.text_field :number, class: "form-control", placeholder: "Game Number" %>
				</div>
			</div>

			<div class="form-group">
				<div class="control-label col-sm-offset-2 col-sm-2">
					<%= f.label :Player1_id, "Player 1" %>
				</div>
				<div class="col-sm-4">
					<%= f.text_field :Player1_id, class: "form-control", placeholder: "Player 1" %>
				</div>
			</div>

			<div class="form-group">
				<div class="control-label col-sm-offset-2 col-sm-2">
					<%= f.label :Player2_id, "Player 2" %>
				</div>
				<div class="col-sm-4">
					<%= f.text_field :Player2_id, class: "form-control", placeholder: "Player 2" %>
				</div>
			</div>

			<div class="form-group">
				<div class="control-label col-sm-offset-2 col-sm-2">
					<%= f.label :winner %>
				</div>
				<div class="col-sm-4">
					<%= f.text_field :winner, class: "form-control", placeholder: "Winner" %>
				</div>
			</div>

			<div class="form-group">
				<div class="control-label col-sm-offset-2 col-sm-2">
					<%= f.label :skunk %>
				</div>
				<div class="col-sm-4">
					<%= f.text_field :skunk, class: "form-control", placeholder: "Skunk?" %>
				</div>
			</div>

			<div class="form-group">
				<div class="control-label col-sm-offset-2 col-sm-2">
					<%= f.label :perfect_hand %>
				</div>
				<div class="col-sm-4">
					<%= f.text_field :perfect_hand, class: "form-control", placeholder: "Perfect Hand" %>
				</div>
			</div>

			<div class="form-group">
				<div class="control-label col-sm-offset-2 col-sm-2">
					<%= f.label :muggins_points %>
				</div>
				<div class="col-sm-4">
					<%= f.text_field :muggins_points, class: "form-control", placeholder: "Muggins Points" %>
				</div>
			</div>

			<div class="form-group">
				<div class="control-label col-sm-offset-2 col-sm-2">
					<%= f.label :misdeals %>
				</div>
				<div class="col-sm-4">
					<%= f.text_field :misdeals, class: "form-control", placeholder: "Misdeals" %>
				</div>
			</div>

			<div class="form-group">
				<div class='col-sm-offset-4 col-sm-6'>
					<%= f.submit class: "btn btn-primary btn-sm" %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/games/_game.html.erb
<% obj.each do |game| %>
	<div class="row">
		<div class="col-lg-offset-2 col-lg-8 col-xs-12">
			<div class="well well-lg">
					<h1 class="game-title"><%= link_to game.type_of_game, game_path(game) %></h1>
					<h2 class="game-winner">Game #<%= game.number %> - Winner: <%= game.winner %></h2>
				<div class="game-body">
					<div class="row">
						<div class="col-md-4 col-xs-4">
							Player 1: <%= game.user.username %>
						</div>
						<div class="col-md-4 col-xs-4">
							Skunk?: <%= game.skunk %>
						</div>
						<div class="col-md-4 col-xs-4">
							Muggins Points: <%= game.muggins_points %>
						</div>
					</div>
					<div class="row">
						<div class="col-md-4 col-xs-4">
							Player 2: <%= game.Player2_id %>
						</div>
						<div class="col-md-4 col-xs-4">
							<%= pluralize(game.perfect_hand, "Perfect Hand") %>
						</div>
						<div class="col-md-4 col-xs-4">
							Misdeals: <%= game.misdeals %>
						</div>
					</div>

					<div class="game-meta-details">
						<small>
							Created by: <%= game.user.username if game.user %>,
							<%= time_ago_in_words(game.created_at) %> ago,
							last updated: <%= time_ago_in_words(game.updated_at) %> ago
						</small>
					</div>
				</div>

				<div class="game-body-mobile">
					<div class="row">
						<div class="col-xs-12 center">
							<h3>Player 1: <%= game.Player1_id %></h3>
							<h3>Vs</h3>
							<h3>Player 2: <%= game.Player2_id %></h3>
							<li>Skunk?: <%= game.skunk %></li>
							<li>Muggins Points: <%= game.muggins_points %></li>
							<li><%= pluralize(game.perfect_hand, "Perfect Hand") %></li>
							<li>Misdeals: <%= game.misdeals %></li>
						</div>
					</div>

					<div class="game-meta-details">
						<small>
							Created by: <%= game.user.username if game.user %>,
							<%= time_ago_in_words(game.created_at) %> ago,
							last updated: <%= time_ago_in_words(game.updated_at) %> ago
						</small>
					</div>
				</div>
				<% if logged_in? && (current_user == game.user || current_user.admin?) %>
					<%= link_to "Edit this game", edit_game_path(game), class: "btn btn-xs btn-primary" %>
					<%= link_to "Delete Game", game_path(game), method: :delete, data: {confirm: "Are you sure you want to delete this game?"}, class: "btn btn-xs btn-danger" %>
				<% end %>
			</div>
		</div>
	</div>
<% end %>

app/views/games/edit.html.erb
<h1>Edit Game</h1>

<%= render 'form' %>

app/views/games/index.html.erb
<h1>All Games</h1>
<div class="center">
	<%= will_paginate %>
</div>
<%= render 'game', obj: @games %>
<div class="center">
	<%= will_paginate %>
</div>

app/views/games/new.html.erb
<h1> New Game </h1>

<%= render 'form' %>

app/views/games/show.html.erb
<div class="well show-game col-xs-12">
	<% if @game.user %>
	<ul class="listing">
		<div class="row center">
			<h2><%= @game.type_of_game %></h2>
			<div class="col-md-4 col-md-offest-4">
				<li>Created by:</li>
				<li><%= link_to gravatar_for(@game.user), user_path(@game.user) %></li>
				<li class="game-type">
					<%= link_to @game.user.username, user_path(@game.user) %>
				</li>
				<li><small>
					<%= pluralize(@game.user.games.count, "game") if @game.user.games %>
				</small></li>
			</div>

			<div class="col-md-4">
				<li>Player 1: <%= @game.Player1_id %></li>
				<li>Player 2: <%= @game.Player2_id %></li>
				<li>Winner: <%= @game.winner %></li>
				<li>Skunk?: <%= @game.skunk %></li>
				<li><%= pluralize(@game.perfect_hand, "Perfect Hand") %></li>
				<li>Muggins Points: <%= @game.muggins_points %></li>
				<li>Misdeals: <%= @game.misdeals %></li>
			</div>

		</div>
	</ul>
	<% end %>
	<h4 class="center"><strong>Game Number: </strong><%= @game.number %></h4>
		<div class="game-actions center">
			<%= link_to "View all games", games_path, class: "btn btn-xs btn-success" %>
			<% if logged_in? && (current_user == @game.user || current_user.admin?) %>
				<%= link_to "Edit this game", edit_game_path(@game), class: "btn btn-xs btn-primary" %>
				<%= link_to "Delete Game", game_path(@game), method: :delete, data: {confirm: "Are you sure you want to delete this game?"}, class: "btn btn-xs btn-danger" %>
			<% end %>
		</div>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-xs-12">
		<% flash.each do |name, msg| %>
			<div class='alert alert-<%="#{name}" %>'>
				<a href="#" class="close" data-dismiss="alert">&#215;</a>
				<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
			</div>
		<% end %>
	</div>
</div>

<script type="text/javascript">
                $(function() {
                setTimeout(function(){
                $('.alert').slideUp(200);
                }, 1100);
                });
</script>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Goochme", root_path, class: 'navbar-brand', id: "logo" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
          <li><%= link_to "New Game", new_game_path, class: 'navbar-links' %></li>
        <% end %>
        <li class="dropdown navbar-links">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Pages <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Games", games_path %></li>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Rules", rules_path %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Profile", edit_user_path(current_user), class: 'navbar-links' %></li>
          <li><%= link_to "Logout", logout_path, method: :delete, class: 'navbar-links' %></li>
        <% else %>
          <li><%= link_to "Login", login_path, class: 'navbar-links' %></li>
          <li><%= link_to "Sign Up", signup_path, class: 'navbar-links' %></li>
        <% end %>
        <% if logged_in? and current_user.admin? %>
          <li><%= link_to "admin", "", id: "admin" %><li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Goochme.com</title>
    <%= favicon_link_tag 'iphone_home_icon.png', :rel => 'apple-touch-icon', :type => 'image/png' %>
    <link href="/assets/favicon.png" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <% if @nav_true %>
        <%= render 'layouts/nav' %>
      <% end %>

      <%= render 'layouts/messages' %>
      <%= yield %>

      <% if @footer_true %>
        <div class="footer center">
          <p>&copy; Goochme.com 2015</p>
        </div>
      <% end %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
	<div class="page-header">
	  <h1>Goochme</h1>
    <h4 class="center"><small>Gimmie the Gooch!</small></h4>
    <h1>Cribbage Game Tracker</h1>
	</div>
		<h3 class="center">Cribbage is a family tradition played for bragging rights.</h3>
    <hr>
	<div class="row">
    <div class="well col-lg-offset-2 col-lg-8 col-xs-offset-1 col-xs-10 center">
      <h3>Where did the term "Gooch" come from?</h3>
      <h2 class="left">While trying to remember the term "Knobs", Kelly's sister called it a "Gooch".</h2>
    </div>
    <div class="well col-lg-offset-2 col-lg-8 col-xs-offset-1 col-xs-10 center">
      <h3>Bragging Rights</h3>
      <h2 class="left">After years of playing Cribbage, we needed a way to track the results of all our games.</h2>
      </div>
    <div class="well col-lg-offset-2 col-lg-8 col-xs-offset-1 col-xs-10 center">
      <h3>Perfect Hands</h3>
      <h2 class="left">Only one player has achieved this feat...</h2>
      </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>Goochme</h1>
  <h2>Cribbage Game Tracker</h2>
</div>
<!-- <div class="container center">
  <div class="row">
    <div class="col-sm-4">
      <h3 class="midrow">View Games</h3>
      <h2>Browse games and sign up later</h2>
      <p><%= link_to "Browse Previous Games", "", class: "btn btn-primary btn-small" %></p>
    </div>
    <div class="col-sm-4">
      <h3 class="midrow">View Games</h3>
      <h2>Browse games and sign up later</h2>
      <p><%= link_to "Browse Previous Games", "", class: "btn btn-primary btn-small" %></p>
    </div>
    <div class="col-sm-4">
      <h3 class="midrow">View Games</h3>
      <h2>Browse games and sign up later</h2>
      <p><%= link_to "Browse Previous Games", "", class: "btn btn-primary btn-small" %></p>
    </div>
  </div>
</div> -->

app/views/pages/login.html.erb
<div id="loginModal" class="modal show" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
	  <div class="modal-content-login">
	    <div class="modal-body">
	      <form class="form col-md-12 center-block">
	        <div class="form-group">
	          <input type="text" class="form-control input-lg" placeholder="Email">
	        </div>
	        <div class="form-group">
	          <input type="password" class="form-control input-lg" placeholder="Password">
	        </div>
	        <div class="form-group">
	          <button class="btn btn-primary btn-lg btn-block">Sign In</button>
	          <span class="pull-right"><a href="#">Register</a></span>
	        </div>
	      </form>
	    </div>
	  </div>
  </div>
</div>

app/views/pages/rules.html.erb
<div class="container">
	<div class="page-header">
	  <h1>Rules</h1>
    <h2>The Rules of the Game</h2>
	</div>
</div>
<div class="container">
	</div>
	<div class="row">
    <div class="well col-lg-offset-2 col-lg-8 col-xs-offset-1 col-xs-10 center">
      <h3>House Rule #1</h3>
      <h2 class="center">Cut for deal, low card has first crib.</h2>
    </div>
    <div class="well col-lg-offset-2 col-lg-8 col-xs-offset-1 col-xs-10 center">
      <h3>House Rule #2</h3>
      <h2 class="center">Pegs must be reset before first card is played, otherwise you start from where you left off.</h2>
      </div>
    <div class="well col-lg-offset-2 col-lg-8 col-xs-offset-1 col-xs-10 center">
      <h3>House Rule #3</h3>
      <h2 class="center">Muggins points are available.</h2>
      </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="panel panel-danger">
				<div class="panel-heading">
					<h2 class="panel-title">
						<%= pluralize(obj.errors.count, "error") %>
						game could not be saved:
					</h2>
					<div class="panel-body">
						<ul>
							<%= obj.errors.full_messages.each do |msg| %>
								<li><%= msg %></li>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class="row">
	<div class="col-xs-12">
		<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
			<div class="form-group">
				<div class="control-label col-sm-offset-1 col-sm-2">
					<%= f.label :username %>
				</div>
				<div class="col-sm-6">
					<%= f.text_field :username, class: "form-control", placeholder: "Username", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-offset-1 col-sm-2">
					<%= f.label :email %>
				</div>
				<div class="col-sm-6">
					<%= f.email_field :email, class: "form-control", placeholder: "Email" %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-offset-1 col-sm-2">
					<%= f.label :password %>
				</div>
				<div class="col-sm-6">
					<%= f.password_field :password, class: "form-control", placeholder: "Enter Password" %>
				</div>
			</div>
			<div class="form-group">
				<div class='col-sm-offset-3 col-sm-6'>
					<%= f.submit(@user.new_record? ? "Signup" : "Update Account", class: "btn btn-primary btn-sm") %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/users/edit.html.erb
<h1>Edit your account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>All Gooch Players</h1>
	<% @users.each do |user| %>
		<ul class="listing center">
			<div class="row">
				<div class="well col-xs-offset-2 col-xs-8">
					<li><%= link_to gravatar_for(user), user_path(user) %></li>
					<li class="game-type">
						<%= link_to user.username, user_path(user) %>
					</li>
					<li><small><%= pluralize(user.games.count, "game") if user.games %></small></li>
					<% if logged_in? and current_user.admin? %>
						<li><%= link_to "Delete this user", user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete this user and all associated games?" } %></li>
					<% end %>
				</div>
			</div>
		</ul>
	<% end %>
	<div class="center">
		<%= will_paginate %>
	</div>

app/views/users/new.html.erb
<h1>Sign up for GoochMe</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.username.capitalize %></h1>
<div class="row">
	<div class="col-xs-offset-4 well col-xs-4 center">
		<%= gravatar_for @user %>
	</div>
</div>
<div class="col-xs-offset-4 col-xs-4 center">
	<%= will_paginate @user_games %>
</div>
<%= render 'games/game', obj: @user_games %>
<div class="col-xs-offset-4 col-xs-4 center">
	<%= will_paginate @user_games %>
</div>